# Copyright (C) 2016 PAxNextbit
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_COPY_FILES += \
    out/proprietary/app/datastatusnotification/datastatusnotification.apk:system/app/datastatusnotification/datastatusnotification.apk \
    out/proprietary/app/fastdormancy/fastdormancy.apk:system/app/fastdormancy/fastdormancy.apk \
    out/proprietary/app/shutdownlistener/shutdownlistener.apk:system/app/shutdownlistener/shutdownlistener.apk \
    out/proprietary/app/TimeService/TimeService.apk:system/app/TimeService/TimeService.apk \
    out/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    out/proprietary/bin/btnvtool:system/bin/btnvtool \
    out/proprietary/bin/cnd:system/bin/cnd \
    out/proprietary/bin/cnss-daemon:system/bin/cnss-daemon \
    out/proprietary/bin/cnss_diag:system/bin/cnss_diag \
    out/proprietary/bin/dpmd:system/bin/dpmd \
    out/proprietary/bin/energy-awareness:system/bin/energy-awareness \
    out/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    out/proprietary/bin/imscmservice:system/bin/imscmservice \
    out/proprietary/bin/imsdatadaemon:system/bin/imsdatadaemon \
    out/proprietary/bin/imsqmidaemon:system/bin/imsqmidaemon \
    out/proprietary/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon \
    out/proprietary/bin/iop:system/bin/iop \
    out/proprietary/bin/ipacm-diag:system/bin/ipacm-diag \
    out/proprietary/bin/irsc_util:system/bin/irsc_util \
    out/proprietary/bin/loc_launcher:system/bin/loc_launcher \
    out/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    out/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    out/proprietary/bin/msm_irqbalance:system/bin/msm_irqbalance \
    out/proprietary/bin/netmgrd:system/bin/netmgrd \
    out/proprietary/bin/pm-proxy:system/bin/pm-proxy \
    out/proprietary/bin/pm-service:system/bin/pm-service \
    out/proprietary/bin/qmuxd:system/bin/qmuxd \
    out/proprietary/bin/qseecomd:system/bin/qseecomd \
    out/proprietary/bin/radish:system/bin/radish \
    out/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    out/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    out/proprietary/bin/time_daemon:system/bin/time_daemon \
    out/proprietary/bin/wcnss_filter:system/bin/wcnss_filter \
    out/proprietary/etc/cne/andsfCne.xml:system/etc/cne/andsfCne.xml \
    out/proprietary/etc/cne/SwimConfig.xml:system/etc/cne/SwimConfig.xml \
    out/proprietary/etc/data/dsi_config.xml:system/etc/data/dsi_config.xml \
    out/proprietary/etc/data/netmgr_config.xml:system/etc/data/netmgr_config.xml \
    out/proprietary/etc/data/qmi_config.xml:system/etc/data/qmi_config.xml \
    out/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    out/proprietary/etc/dpm/nsrm/NsrmConfiguration.xml:system/etc/dpm/nsrm/NsrmConfiguration.xml \
    out/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    out/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    out/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    out/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    out/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    out/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    out/proprietary/etc/firmware/cpp_firmware_v1_6_0.fw:system/etc/firmware/cpp_firmware_v1_6_0.fw \
    out/proprietary/etc/firmware/cpp_firmware_v1_8_0.fw:system/etc/firmware/cpp_firmware_v1_8_0.fw \
    out/proprietary/etc/firmware/TP_Firmware_nbq_ebbg.img:system/etc/firmware/TP_Firmware_nbq_ebbg.img \
    out/proprietary/etc/firmware/TP_Firmware_nbq_ebbg_V29.img:system/etc/firmware/TP_Firmware_nbq_ebbg_V29.img \
    out/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    out/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    out/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    out/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    out/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    out/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    out/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    out/proprietary/etc/nxp/settings/os/alarm/1/HQ_KS_13X18_DUMBO.eq:system/etc/nxp/settings/os/alarm/1/HQ_KS_13X18_DUMBO.eq \
    out/proprietary/etc/nxp/settings/os/alarm/1/HQ_KS_13X18_DUMBO.preset:system/etc/nxp/settings/os/alarm/1/HQ_KS_13X18_DUMBO.preset \
    out/proprietary/etc/nxp/settings/os/alarm/2/HQ_KS_13X18_DUMBO.eq:system/etc/nxp/settings/os/alarm/2/HQ_KS_13X18_DUMBO.eq \
    out/proprietary/etc/nxp/settings/os/alarm/2/HQ_KS_13X18_DUMBO.preset:system/etc/nxp/settings/os/alarm/2/HQ_KS_13X18_DUMBO.preset \
    out/proprietary/etc/nxp/settings/os/alarm/3/HQ_KS_13X18_DUMBO.eq:system/etc/nxp/settings/os/alarm/3/HQ_KS_13X18_DUMBO.eq \
    out/proprietary/etc/nxp/settings/os/alarm/3/HQ_KS_13X18_DUMBO.preset:system/etc/nxp/settings/os/alarm/3/HQ_KS_13X18_DUMBO.preset \
    out/proprietary/etc/nxp/settings/os/alarm/4/HQ_KS_13X18_DUMBO.eq:system/etc/nxp/settings/os/alarm/4/HQ_KS_13X18_DUMBO.eq \
    out/proprietary/etc/nxp/settings/os/alarm/4/HQ_KS_13X18_DUMBO.preset:system/etc/nxp/settings/os/alarm/4/HQ_KS_13X18_DUMBO.preset \
    out/proprietary/etc/nxp/settings/os/keytone/1/HQ_KS_13X18_DUMBO.eq:system/etc/nxp/settings/os/keytone/1/HQ_KS_13X18_DUMBO.eq \
    out/proprietary/etc/nxp/settings/os/keytone/1/HQ_KS_13X18_DUMBO.preset:system/etc/nxp/settings/os/keytone/1/HQ_KS_13X18_DUMBO.preset \
    out/proprietary/etc/nxp/settings/os/keytone/2/HQ_KS_13X18_DUMBO.eq:system/etc/nxp/settings/os/keytone/2/HQ_KS_13X18_DUMBO.eq \
    out/proprietary/etc/nxp/settings/os/keytone/2/HQ_KS_13X18_DUMBO.preset:system/etc/nxp/settings/os/keytone/2/HQ_KS_13X18_DUMBO.preset \
    out/proprietary/etc/nxp/settings/os/keytone/3/HQ_KS_13X18_DUMBO.eq:system/etc/nxp/settings/os/keytone/3/HQ_KS_13X18_DUMBO.eq \
    out/proprietary/etc/nxp/settings/os/keytone/3/HQ_KS_13X18_DUMBO.preset:system/etc/nxp/settings/os/keytone/3/HQ_KS_13X18_DUMBO.preset \
    out/proprietary/etc/nxp/settings/os/keytone/4/HQ_KS_13X18_DUMBO.eq:system/etc/nxp/settings/os/keytone/4/HQ_KS_13X18_DUMBO.eq \
    out/proprietary/etc/nxp/settings/os/keytone/4/HQ_KS_13X18_DUMBO.preset:system/etc/nxp/settings/os/keytone/4/HQ_KS_13X18_DUMBO.preset \
    out/proprietary/etc/nxp/settings/os/playback/1/coldboot.patch:system/etc/nxp/settings/os/playback/1/coldboot.patch \
    out/proprietary/etc/nxp/settings/os/playback/1/devkit_Release.parms:system/etc/nxp/settings/os/playback/1/devkit_Release.parms \
    out/proprietary/etc/nxp/settings/os/playback/1/HQ_KS_13X18_DUMBO.eq:system/etc/nxp/settings/os/playback/1/HQ_KS_13X18_DUMBO.eq \
    out/proprietary/etc/nxp/settings/os/playback/1/HQ_KS_13X18_DUMBO.preset:system/etc/nxp/settings/os/playback/1/HQ_KS_13X18_DUMBO.preset \
    out/proprietary/etc/nxp/settings/os/playback/1/speaker.speaker:system/etc/nxp/settings/os/playback/1/speaker.speaker \
    out/proprietary/etc/nxp/settings/os/playback/1/TFA9887_N1D2_2_4_1.patch:system/etc/nxp/settings/os/playback/1/TFA9887_N1D2_2_4_1.patch \
    out/proprietary/etc/nxp/settings/os/playback/1/TFA9887_N1D2.config:system/etc/nxp/settings/os/playback/1/TFA9887_N1D2.config \
    out/proprietary/etc/nxp/settings/os/playback/2/coldboot.patch:system/etc/nxp/settings/os/playback/2/coldboot.patch \
    out/proprietary/etc/nxp/settings/os/playback/2/devkit_Release.parms:system/etc/nxp/settings/os/playback/2/devkit_Release.parms \
    out/proprietary/etc/nxp/settings/os/playback/2/HQ_KS_13X18_DUMBO.eq:system/etc/nxp/settings/os/playback/2/HQ_KS_13X18_DUMBO.eq \
    out/proprietary/etc/nxp/settings/os/playback/2/HQ_KS_13X18_DUMBO.preset:system/etc/nxp/settings/os/playback/2/HQ_KS_13X18_DUMBO.preset \
    out/proprietary/etc/nxp/settings/os/playback/2/speaker.speaker:system/etc/nxp/settings/os/playback/2/speaker.speaker \
    out/proprietary/etc/nxp/settings/os/playback/2/TFA9887_N1D2_2_4_1.patch:system/etc/nxp/settings/os/playback/2/TFA9887_N1D2_2_4_1.patch \
    out/proprietary/etc/nxp/settings/os/playback/2/TFA9887_N1D2.config:system/etc/nxp/settings/os/playback/2/TFA9887_N1D2.config \
    out/proprietary/etc/nxp/settings/os/playback/3/coldboot.patch:system/etc/nxp/settings/os/playback/3/coldboot.patch \
    out/proprietary/etc/nxp/settings/os/playback/3/devkit_Release.parms:system/etc/nxp/settings/os/playback/3/devkit_Release.parms \
    out/proprietary/etc/nxp/settings/os/playback/3/HQ_KS_13X18_DUMBO.eq:system/etc/nxp/settings/os/playback/3/HQ_KS_13X18_DUMBO.eq \
    out/proprietary/etc/nxp/settings/os/playback/3/HQ_KS_13X18_DUMBO.preset:system/etc/nxp/settings/os/playback/3/HQ_KS_13X18_DUMBO.preset \
    out/proprietary/etc/nxp/settings/os/playback/3/speaker.speaker:system/etc/nxp/settings/os/playback/3/speaker.speaker \
    out/proprietary/etc/nxp/settings/os/playback/3/TFA9887_N1D2_2_4_1.patch:system/etc/nxp/settings/os/playback/3/TFA9887_N1D2_2_4_1.patch \
    out/proprietary/etc/nxp/settings/os/playback/3/TFA9887_N1D2.config:system/etc/nxp/settings/os/playback/3/TFA9887_N1D2.config \
    out/proprietary/etc/nxp/settings/os/playback/4/coldboot.patch:system/etc/nxp/settings/os/playback/4/coldboot.patch \
    out/proprietary/etc/nxp/settings/os/playback/4/devkit_Release.parms:system/etc/nxp/settings/os/playback/4/devkit_Release.parms \
    out/proprietary/etc/nxp/settings/os/playback/4/HQ_KS_13X18_DUMBO.eq:system/etc/nxp/settings/os/playback/4/HQ_KS_13X18_DUMBO.eq \
    out/proprietary/etc/nxp/settings/os/playback/4/HQ_KS_13X18_DUMBO.preset:system/etc/nxp/settings/os/playback/4/HQ_KS_13X18_DUMBO.preset \
    out/proprietary/etc/nxp/settings/os/playback/4/speaker.speaker:system/etc/nxp/settings/os/playback/4/speaker.speaker \
    out/proprietary/etc/nxp/settings/os/playback/4/TFA9887_N1D2_2_4_1.patch:system/etc/nxp/settings/os/playback/4/TFA9887_N1D2_2_4_1.patch \
    out/proprietary/etc/nxp/settings/os/playback/4/TFA9887_N1D2.config:system/etc/nxp/settings/os/playback/4/TFA9887_N1D2.config \
    out/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    out/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    out/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
    out/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    out/proprietary/etc/permissions/com.qualcomm.qti.Performance.xml:system/etc/permissions/com.qualcomm.qti.Performance.xml \
    out/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    out/proprietary/etc/permissions/ConnectivityExt.xml:system/etc/permissions/ConnectivityExt.xml \
    out/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    out/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    out/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    out/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    out/proprietary/etc/permissions/qti_telephony_common.xml:system/etc/permissions/qti_telephony_common.xml \
    out/proprietary/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml \
    out/proprietary/etc/sensors/hals.conf:system/etc/sensors/hals.conf \
    out/proprietary/etc/sensors/sensor_def_qcomdev.conf:system/etc/sensors/sensor_def_qcomdev.conf \
    out/proprietary/etc/sensors/sensor_fih_def_nbq_EVT1C_qcomdev.conf:system/etc/sensors/sensor_fih_def_nbq_EVT1C_qcomdev.conf \
    out/proprietary/etc/sensors/sensor_fih_def_nbq_qcomdev.conf:system/etc/sensors/sensor_fih_def_nbq_qcomdev.conf \
    out/proprietary/etc/thermal-engine-8992.conf:system/etc/thermal-engine-8992.conf \
    out/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    out/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    out/proprietary/framework/ConnectivityExt.jar:system/framework/ConnectivityExt.jar \
    out/proprietary/framework/qcnvitems.jar:system/framework/qcnvitems.jar \
    out/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    out/proprietary/framework/qti-telephony-common.jar:system/framework/qti-telephony-common.jar \
    out/proprietary/framework/QtiTelephonyServicelibrary.jar:system/framework/QtiTelephonyServicelibrary.jar \
    out/proprietary/lib64/hw/fingerprint.msm8992.so:system/lib64/hw/fingerprint.msm8992.so \
    out/proprietary/lib64/libFIHNxp.so:system/lib64/libFIHNxp.so \
    out/proprietary/lib64/lib_fpc_tac_shared.so:system/lib64/lib_fpc_tac_shared.so \
    out/proprietary/lib64/libloc_api_v02.so:system/lib64/libloc_api_v02.so \
    out/proprietary/lib64/libqti-iop.so:system/lib64/libqti-iop.so \
    out/proprietary/lib64/libstagefright_soft_flacdec.so:system/lib64/libstagefright_soft_flacdec.so \
    out/proprietary/lib64/libtfa98xx_hal.so:system/lib64/libtfa98xx_hal.so \
    out/proprietary/lib64/libtfa98xx.so:system/lib64/libtfa98xx.so \
    out/proprietary/lib/hw/camera.msm8992.so:system/lib/hw/camera.msm8992.so \
    out/proprietary/lib/hw/fingerprint.msm8992.so:system/lib/hw/fingerprint.msm8992.so \
    out/proprietary/lib/libFIHNxp.so:system/lib/libFIHNxp.so \
    out/proprietary/lib/lib_fpc_tac_shared.so:system/lib/lib_fpc_tac_shared.so \
    out/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    out/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    out/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    out/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    out/proprietary/lib/libmorpho_image_stab4.so:system/lib/libmorpho_image_stab4.so \
    out/proprietary/lib/libmorpho_movie_stab4.so:system/lib/libmorpho_movie_stab4.so \
    out/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    out/proprietary/lib/libqti-iop.so:system/lib/libqti-iop.so \
    out/proprietary/lib/libstagefright_soft_flacdec.so:system/lib/libstagefright_soft_flacdec.so \
    out/proprietary/lib/libtfa98xx_hal.so:system/lib/libtfa98xx_hal.so \
    out/proprietary/lib/libtfa98xx.so:system/lib/libtfa98xx.so \
    out/proprietary/priv-app/CNEService/CNEService.apk:system/priv-app/CNEService/CNEService.apk \
    out/proprietary/priv-app/com.qualcomm.location/com.qualcomm.location.apk:system/priv-app/com.qualcomm.location/com.qualcomm.location.apk \
    out/proprietary/priv-app/dpmserviceapp/dpmserviceapp.apk:system/priv-app/dpmserviceapp/dpmserviceapp.apk \
    out/proprietary/priv-app/qcrilmsgtunnel/qcrilmsgtunnel.apk:system/priv-app/qcrilmsgtunnel/qcrilmsgtunnel.apk \
    out/proprietary/vendor/app/ims/ims.apk:system/vendor/app/ims/ims.apk \
    out/proprietary/vendor/app/imssettings/imssettings.apk:system/vendor/app/imssettings/imssettings.apk \
    out/proprietary/vendor/bin/perfd:system/vendor/bin/perfd \
    out/proprietary/vendor/bin/qti:system/vendor/bin/qti \
    out/proprietary/vendor/bin/slim_daemon:system/vendor/bin/slim_daemon \
    out/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    out/proprietary/vendor/etc/perf-profile0.conf:system/vendor/etc/perf-profile0.conf \
    out/proprietary/vendor/etc/perf-profile1.conf:system/vendor/etc/perf-profile1.conf \
    out/proprietary/vendor/etc/perf-profile2.conf:system/vendor/etc/perf-profile2.conf \
    out/proprietary/vendor/etc/perf-profile3.conf:system/vendor/etc/perf-profile3.conf \
    out/proprietary/vendor/etc/perf-profile4.conf:system/vendor/etc/perf-profile4.conf \
    out/proprietary/vendor/etc/perf-profile5.conf:system/vendor/etc/perf-profile5.conf \
    out/proprietary/vendor/firmware/fpctzappfingerprint.b00:system/vendor/firmware/fpctzappfingerprint.b00 \
    out/proprietary/vendor/firmware/fpctzappfingerprint.b01:system/vendor/firmware/fpctzappfingerprint.b01 \
    out/proprietary/vendor/firmware/fpctzappfingerprint.b02:system/vendor/firmware/fpctzappfingerprint.b02 \
    out/proprietary/vendor/firmware/fpctzappfingerprint.b03:system/vendor/firmware/fpctzappfingerprint.b03 \
    out/proprietary/vendor/firmware/fpctzappfingerprint.mdt:system/vendor/firmware/fpctzappfingerprint.mdt \
    out/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    out/proprietary/vendor/lib64/egl/eglSubDriverAndroid.so:system/vendor/lib64/egl/eglSubDriverAndroid.so \
    out/proprietary/vendor/lib64/egl/libEGL_adreno.so:system/vendor/lib64/egl/libEGL_adreno.so \
    out/proprietary/vendor/lib64/egl/libGLESv1_CM_adreno.so:system/vendor/lib64/egl/libGLESv1_CM_adreno.so \
    out/proprietary/vendor/lib64/egl/libGLESv2_adreno.so:system/vendor/lib64/egl/libGLESv2_adreno.so \
    out/proprietary/vendor/lib64/egl/libq3dtools_adreno.so:system/vendor/lib64/egl/libq3dtools_adreno.so \
    out/proprietary/vendor/lib64/egl/libq3dtools_esx.so:system/vendor/lib64/egl/libq3dtools_esx.so \
    out/proprietary/vendor/lib64/egl/libQTapGLES.so:system/vendor/lib64/egl/libQTapGLES.so \
    out/proprietary/vendor/lib64/hw/activity_recognition.msm8992.so:system/vendor/lib64/hw/activity_recognition.msm8992.so \
    out/proprietary/vendor/lib64/hw/flp.default.so:system/vendor/lib64/hw/flp.default.so \
    out/proprietary/vendor/lib64/hw/gatekeeper.msm8992.so:system/vendor/lib64/hw/gatekeeper.msm8992.so \
    out/proprietary/vendor/lib64/hw/keystore.msm8992.so:system/vendor/lib64/hw/keystore.msm8992.so \
    out/proprietary/vendor/lib64/hw/vulkan.msm8992.so:system/vendor/lib64/hw/vulkan.msm8992.so \
    out/proprietary/vendor/lib64/libacdb-fts.so:system/vendor/lib64/libacdb-fts.so \
    out/proprietary/vendor/lib64/libacdbloader.so:system/vendor/lib64/libacdbloader.so \
    out/proprietary/vendor/lib64/libacdbrtac.so:system/vendor/lib64/libacdbrtac.so \
    out/proprietary/vendor/lib64/libadiertac.so:system/vendor/lib64/libadiertac.so \
    out/proprietary/vendor/lib64/libadreno_utils.so:system/vendor/lib64/libadreno_utils.so \
    out/proprietary/vendor/lib64/libadsprpc.so:system/vendor/lib64/libadsprpc.so \
    out/proprietary/vendor/lib64/libalarmservice_jni.so:system/vendor/lib64/libalarmservice_jni.so \
    out/proprietary/vendor/lib64/libaudcal.so:system/vendor/lib64/libaudcal.so \
    out/proprietary/vendor/lib64/libavenhancements.so:system/vendor/lib64/libavenhancements.so \
    out/proprietary/vendor/lib64/libbccQTI.so:system/vendor/lib64/libbccQTI.so \
    out/proprietary/vendor/lib64/libbtnv.so:system/vendor/lib64/libbtnv.so \
    out/proprietary/vendor/lib64/libC2D2.so:system/vendor/lib64/libC2D2.so \
    out/proprietary/vendor/lib64/libc2d30-a4xx.so:system/vendor/lib64/libc2d30-a4xx.so \
    out/proprietary/vendor/lib64/libCB.so:system/vendor/lib64/libCB.so \
    out/proprietary/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so \
    out/proprietary/vendor/lib64/libcneconn.so:system/vendor/lib64/libcneconn.so \
    out/proprietary/vendor/lib64/libcneqmiutils.so:system/vendor/lib64/libcneqmiutils.so \
    out/proprietary/vendor/lib64/libcne.so:system/vendor/lib64/libcne.so \
    out/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    out/proprietary/vendor/lib64/libconnctrl.so:system/vendor/lib64/libconnctrl.so \
    out/proprietary/vendor/lib64/libdataitems.so:system/vendor/lib64/libdataitems.so \
    out/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
    out/proprietary/vendor/lib64/libdisp-aba.so:system/vendor/lib64/libdisp-aba.so \
    out/proprietary/vendor/lib64/lib-dplmedia.so:system/vendor/lib64/lib-dplmedia.so \
    out/proprietary/vendor/lib64/libdpmctmgr.so:system/vendor/lib64/libdpmctmgr.so \
    out/proprietary/vendor/lib64/libdpmfdmgr.so:system/vendor/lib64/libdpmfdmgr.so \
    out/proprietary/vendor/lib64/libdpmframework.so:system/vendor/lib64/libdpmframework.so \
    out/proprietary/vendor/lib64/libdpmnsrm.so:system/vendor/lib64/libdpmnsrm.so \
    out/proprietary/vendor/lib64/libdpmtcm.so:system/vendor/lib64/libdpmtcm.so \
    out/proprietary/vendor/lib64/libdrmfs.so:system/vendor/lib64/libdrmfs.so \
    out/proprietary/vendor/lib64/libdrmtime.so:system/vendor/lib64/libdrmtime.so \
    out/proprietary/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so \
    out/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
    out/proprietary/vendor/lib64/libExtendedExtractor.so:system/vendor/lib64/libExtendedExtractor.so \
    out/proprietary/vendor/lib64/libFlacSwDec.so:system/vendor/lib64/libFlacSwDec.so \
    out/proprietary/vendor/lib64/libflp.so:system/vendor/lib64/libflp.so \
    out/proprietary/vendor/lib64/libgeofence.so:system/vendor/lib64/libgeofence.so \
    out/proprietary/vendor/lib64/libgsl.so:system/vendor/lib64/libgsl.so \
    out/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
    out/proprietary/vendor/lib64/libimscamera_jni.so:system/vendor/lib64/libimscamera_jni.so \
    out/proprietary/vendor/lib64/lib-imscamera.so:system/vendor/lib64/lib-imscamera.so \
    out/proprietary/vendor/lib64/lib-imsdpl.so:system/vendor/lib64/lib-imsdpl.so \
    out/proprietary/vendor/lib64/libimsmedia_jni.so:system/vendor/lib64/libimsmedia_jni.so \
    out/proprietary/vendor/lib64/lib-imsqimf.so:system/vendor/lib64/lib-imsqimf.so \
    out/proprietary/vendor/lib64/lib-imsrcscmclient.so:system/vendor/lib64/lib-imsrcscmclient.so \
    out/proprietary/vendor/lib64/lib-ims-rcscmjni.so:system/vendor/lib64/lib-ims-rcscmjni.so \
    out/proprietary/vendor/lib64/lib-imsrcscmservice.so:system/vendor/lib64/lib-imsrcscmservice.so \
    out/proprietary/vendor/lib64/lib-imsrcscm.so:system/vendor/lib64/lib-imsrcscm.so \
    out/proprietary/vendor/lib64/lib-imsrcs.so:system/vendor/lib64/lib-imsrcs.so \
    out/proprietary/vendor/lib64/lib-imsSDP.so:system/vendor/lib64/lib-imsSDP.so \
    out/proprietary/vendor/lib64/lib-imss.so:system/vendor/lib64/lib-imss.so \
    out/proprietary/vendor/lib64/lib-imsvt.so:system/vendor/lib64/lib-imsvt.so \
    out/proprietary/vendor/lib64/lib-imsxml.so:system/vendor/lib64/lib-imsxml.so \
    out/proprietary/vendor/lib64/libizat_core.so:system/vendor/lib64/libizat_core.so \
    out/proprietary/vendor/lib64/liblbs_core.so:system/vendor/lib64/liblbs_core.so \
    out/proprietary/vendor/lib64/libllvm-glnext.so:system/vendor/lib64/libllvm-glnext.so \
    out/proprietary/vendor/lib64/libllvm-qcom.so:system/vendor/lib64/libllvm-qcom.so \
    out/proprietary/vendor/lib64/libllvm-qgl.so:system/vendor/lib64/libllvm-qgl.so \
    out/proprietary/vendor/lib64/liblocationservice_glue.so:system/vendor/lib64/liblocationservice_glue.so \
    out/proprietary/vendor/lib64/liblocationservice.so:system/vendor/lib64/liblocationservice.so \
    out/proprietary/vendor/lib64/liblowi_client.so:system/vendor/lib64/liblowi_client.so \
    out/proprietary/vendor/lib64/liblowi_wifihal.so:system/vendor/lib64/liblowi_wifihal.so \
    out/proprietary/vendor/lib64/liblqe.so:system/vendor/lib64/liblqe.so \
    out/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    out/proprietary/vendor/lib64/libmm-abl-oem.so:system/vendor/lib64/libmm-abl-oem.so \
    out/proprietary/vendor/lib64/libmm-abl.so:system/vendor/lib64/libmm-abl.so \
    out/proprietary/vendor/lib64/libmm-als.so:system/vendor/lib64/libmm-als.so \
    out/proprietary/vendor/lib64/libmm-disp-apis.so:system/vendor/lib64/libmm-disp-apis.so \
    out/proprietary/vendor/lib64/libmmparser_lite.so:system/vendor/lib64/libmmparser_lite.so \
    out/proprietary/vendor/lib64/libmmparser.so:system/vendor/lib64/libmmparser.so \
    out/proprietary/vendor/lib64/libmm-qdcm.so:system/vendor/lib64/libmm-qdcm.so \
    out/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    out/proprietary/vendor/lib64/libNimsWrap.so:system/vendor/lib64/libNimsWrap.so \
    out/proprietary/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so \
    out/proprietary/vendor/lib64/libperipheral_client.so:system/vendor/lib64/libperipheral_client.so \
    out/proprietary/vendor/lib64/libQBLAS-0.11.38.so:system/vendor/lib64/libQBLAS-0.11.38.so \
    out/proprietary/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so \
    out/proprietary/vendor/lib64/libqcmaputils.so:system/vendor/lib64/libqcmaputils.so \
    out/proprietary/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so \
    out/proprietary/vendor/lib64/libqdp.so:system/vendor/lib64/libqdp.so \
    out/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
    out/proprietary/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so \
    out/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
    out/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
    out/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
    out/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
    out/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
    out/proprietary/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so \
    out/proprietary/vendor/lib64/libqti-iop-client.so:system/vendor/lib64/libqti-iop-client.so \
    out/proprietary/vendor/lib64/libqti-perfd-client.so:system/vendor/lib64/libqti-perfd-client.so \
    out/proprietary/vendor/lib64/libqti_performance.so:system/vendor/lib64/libqti_performance.so \
    out/proprietary/vendor/lib64/libQtiTether.so:system/vendor/lib64/libQtiTether.so \
    out/proprietary/vendor/lib64/libquipc_os_api.so:system/vendor/lib64/libquipc_os_api.so \
    out/proprietary/vendor/lib64/librcc.so:system/vendor/lib64/librcc.so \
    out/proprietary/vendor/lib64/lib-rcsimssjni.so:system/vendor/lib64/lib-rcsimssjni.so \
    out/proprietary/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so \
    out/proprietary/vendor/lib64/libril-qc-radioconfig.so:system/vendor/lib64/libril-qc-radioconfig.so \
    out/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
    out/proprietary/vendor/lib64/librpmb.so:system/vendor/lib64/librpmb.so \
    out/proprietary/vendor/lib64/librs_adreno_sha1.so:system/vendor/lib64/librs_adreno_sha1.so \
    out/proprietary/vendor/lib64/librs_adreno.so:system/vendor/lib64/librs_adreno.so \
    out/proprietary/vendor/lib64/libRSDriver_adreno.so:system/vendor/lib64/libRSDriver_adreno.so \
    out/proprietary/vendor/lib64/lib-rtpcommon.so:system/vendor/lib64/lib-rtpcommon.so \
    out/proprietary/vendor/lib64/lib-rtpcore.so:system/vendor/lib64/lib-rtpcore.so \
    out/proprietary/vendor/lib64/lib-rtpdaemoninterface.so:system/vendor/lib64/lib-rtpdaemoninterface.so \
    out/proprietary/vendor/lib64/lib-rtpsl.so:system/vendor/lib64/lib-rtpsl.so \
    out/proprietary/vendor/lib64/libscale.so:system/vendor/lib64/libscale.so \
    out/proprietary/vendor/lib64/libsensor1.so:system/vendor/lib64/libsensor1.so \
    out/proprietary/vendor/lib64/libsensor_reg.so:system/vendor/lib64/libsensor_reg.so \
    out/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
    out/proprietary/vendor/lib64/libssd.so:system/vendor/lib64/libssd.so \
    out/proprietary/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so \
    out/proprietary/vendor/lib64/libthermalclient.so:system/vendor/lib64/libthermalclient.so \
    out/proprietary/vendor/lib64/libthermalioctl.so:system/vendor/lib64/libthermalioctl.so \
    out/proprietary/vendor/lib64/libtime_genoff.so:system/vendor/lib64/libtime_genoff.so \
    out/proprietary/vendor/lib64/libTimeService.so:system/vendor/lib64/libTimeService.so \
    out/proprietary/vendor/lib64/libulp2.so:system/vendor/lib64/libulp2.so \
    out/proprietary/vendor/lib64/libvendorconn.so:system/vendor/lib64/libvendorconn.so \
    out/proprietary/vendor/lib64/libvoice-svc.so:system/vendor/lib64/libvoice-svc.so \
    out/proprietary/vendor/lib64/libwqe.so:system/vendor/lib64/libwqe.so \
    out/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so \
    out/proprietary/vendor/lib64/libxtadapter.so:system/vendor/lib64/libxtadapter.so \
    out/proprietary/vendor/lib64/libxtwifi_ulp_adaptor.so:system/vendor/lib64/libxtwifi_ulp_adaptor.so \
    out/proprietary/vendor/lib64/sensors.ssc.so:system/vendor/lib64/sensors.ssc.so \
    out/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    out/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    out/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    out/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    out/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    out/proprietary/vendor/lib/egl/libq3dtools_esx.so:system/vendor/lib/egl/libq3dtools_esx.so \
    out/proprietary/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    out/proprietary/vendor/lib/hw/activity_recognition.msm8992.so:system/vendor/lib/hw/activity_recognition.msm8992.so \
    out/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    out/proprietary/vendor/lib/hw/gatekeeper.msm8992.so:system/vendor/lib/hw/gatekeeper.msm8992.so \
    out/proprietary/vendor/lib/hw/keystore.msm8992.so:system/vendor/lib/hw/keystore.msm8992.so \
    out/proprietary/vendor/lib/hw/vulkan.msm8992.so:system/vendor/lib/hw/vulkan.msm8992.so \
    out/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    out/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    out/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    out/proprietary/vendor/lib/libactuator_dw9761b_camcorder.so:system/vendor/lib/libactuator_dw9761b_camcorder.so \
    out/proprietary/vendor/lib/libactuator_dw9761b_camera.so:system/vendor/lib/libactuator_dw9761b_camera.so \
    out/proprietary/vendor/lib/libactuator_dw9761b.so:system/vendor/lib/libactuator_dw9761b.so \
    out/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    out/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    out/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    out/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    out/proprietary/vendor/lib/libavenhancements.so:system/vendor/lib/libavenhancements.so \
    out/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    out/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    out/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    out/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    out/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_common.so:system/vendor/lib/libchromatix_s5k3m2xm_common.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_cpp_hfr_120.so:system/vendor/lib/libchromatix_s5k3m2xm_cpp_hfr_120.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_cpp_hfr_60.so:system/vendor/lib/libchromatix_s5k3m2xm_cpp_hfr_60.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_cpp_hfr_90.so:system/vendor/lib/libchromatix_s5k3m2xm_cpp_hfr_90.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_cpp_liveshot.so:system/vendor/lib/libchromatix_s5k3m2xm_cpp_liveshot.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_cpp_preview.so:system/vendor/lib/libchromatix_s5k3m2xm_cpp_preview.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_cpp_snapshot.so:system/vendor/lib/libchromatix_s5k3m2xm_cpp_snapshot.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_cpp_video.so:system/vendor/lib/libchromatix_s5k3m2xm_cpp_video.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_default_video.so:system/vendor/lib/libchromatix_s5k3m2xm_default_video.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_hfr_120.so:system/vendor/lib/libchromatix_s5k3m2xm_hfr_120.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_hfr_60.so:system/vendor/lib/libchromatix_s5k3m2xm_hfr_60.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_hfr_90.so:system/vendor/lib/libchromatix_s5k3m2xm_hfr_90.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_liveshot.so:system/vendor/lib/libchromatix_s5k3m2xm_liveshot.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_postproc.so:system/vendor/lib/libchromatix_s5k3m2xm_postproc.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_preview.so:system/vendor/lib/libchromatix_s5k3m2xm_preview.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_snapshot.so:system/vendor/lib/libchromatix_s5k3m2xm_snapshot.so \
    out/proprietary/vendor/lib/libchromatix_s5k3m2xm_versions.so:system/vendor/lib/libchromatix_s5k3m2xm_versions.so \
    out/proprietary/vendor/lib/libchromatix_s5k5e2_common.so:system/vendor/lib/libchromatix_s5k5e2_common.so \
    out/proprietary/vendor/lib/libchromatix_s5k5e2_cpp_liveshot.so:system/vendor/lib/libchromatix_s5k5e2_cpp_liveshot.so \
    out/proprietary/vendor/lib/libchromatix_s5k5e2_cpp_preview.so:system/vendor/lib/libchromatix_s5k5e2_cpp_preview.so \
    out/proprietary/vendor/lib/libchromatix_s5k5e2_cpp_snapshot.so:system/vendor/lib/libchromatix_s5k5e2_cpp_snapshot.so \
    out/proprietary/vendor/lib/libchromatix_s5k5e2_cpp_video.so:system/vendor/lib/libchromatix_s5k5e2_cpp_video.so \
    out/proprietary/vendor/lib/libchromatix_s5k5e2_default_video.so:system/vendor/lib/libchromatix_s5k5e2_default_video.so \
    out/proprietary/vendor/lib/libchromatix_s5k5e2_liveshot.so:system/vendor/lib/libchromatix_s5k5e2_liveshot.so \
    out/proprietary/vendor/lib/libchromatix_s5k5e2_postproc.so:system/vendor/lib/libchromatix_s5k5e2_postproc.so \
    out/proprietary/vendor/lib/libchromatix_s5k5e2_preview.so:system/vendor/lib/libchromatix_s5k5e2_preview.so \
    out/proprietary/vendor/lib/libchromatix_s5k5e2_snapshot.so:system/vendor/lib/libchromatix_s5k5e2_snapshot.so \
    out/proprietary/vendor/lib/libchromatix_s5k5e2_versions.so:system/vendor/lib/libchromatix_s5k5e2_versions.so \
    out/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    out/proprietary/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
    out/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
    out/proprietary/vendor/lib/libcne.so:system/vendor/lib/libcne.so \
    out/proprietary/vendor/lib/libconnctrl.so:system/vendor/lib/libconnctrl.so \
    out/proprietary/vendor/lib/libdataitems.so:system/vendor/lib/libdataitems.so \
    out/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    out/proprietary/vendor/lib/libdpmctmgr.so:system/vendor/lib/libdpmctmgr.so \
    out/proprietary/vendor/lib/libdpmfdmgr.so:system/vendor/lib/libdpmfdmgr.so \
    out/proprietary/vendor/lib/libdpmframework.so:system/vendor/lib/libdpmframework.so \
    out/proprietary/vendor/lib/libdpmnsrm.so:system/vendor/lib/libdpmnsrm.so \
    out/proprietary/vendor/lib/libdpmtcm.so:system/vendor/lib/libdpmtcm.so \
    out/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    out/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    out/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
    out/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    out/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    out/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    out/proprietary/vendor/lib/libflash_pmic.so:system/vendor/lib/libflash_pmic.so \
    out/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    out/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    out/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    out/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    out/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    out/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    out/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    out/proprietary/vendor/lib/libjpegdmahw.so:system/vendor/lib/libjpegdmahw.so \
    out/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    out/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    out/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    out/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    out/proprietary/vendor/lib/libllvm-qgl.so:system/vendor/lib/libllvm-qgl.so \
    out/proprietary/vendor/lib/liblocationservice_glue.so:system/vendor/lib/liblocationservice_glue.so \
    out/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    out/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    out/proprietary/vendor/lib/liblqe.so:system/vendor/lib/liblqe.so \
    out/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    out/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    out/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    out/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    out/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    out/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    out/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    out/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    out/proprietary/vendor/lib/libmmcamera2_pp_buf_mgr.so:system/vendor/lib/libmmcamera2_pp_buf_mgr.so \
    out/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    out/proprietary/vendor/lib/libmmcamera2_q3a_core.so:system/vendor/lib/libmmcamera2_q3a_core.so \
    out/proprietary/vendor/lib/libmmcamera2_sensor_debug.so:system/vendor/lib/libmmcamera2_sensor_debug.so \
    out/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    out/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    out/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    out/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    out/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    out/proprietary/vendor/lib/libmmcamera_cac2_lib.so:system/vendor/lib/libmmcamera_cac2_lib.so \
    out/proprietary/vendor/lib/libmmcamera_dw9761b_eeprom.so:system/vendor/lib/libmmcamera_dw9761b_eeprom.so \
    out/proprietary/vendor/lib/libmmcamera_eeprom_util.so:system/vendor/lib/libmmcamera_eeprom_util.so \
    out/proprietary/vendor/lib/libmmcamera_eztune_module.so:system/vendor/lib/libmmcamera_eztune_module.so \
    out/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    out/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    out/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    out/proprietary/vendor/lib/libmmcamera_isp_abf44.so:system/vendor/lib/libmmcamera_isp_abf44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_bcc44.so:system/vendor/lib/libmmcamera_isp_bcc44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_be_stats44.so:system/vendor/lib/libmmcamera_isp_be_stats44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_bf_scale_stats44.so:system/vendor/lib/libmmcamera_isp_bf_scale_stats44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_bf_stats44.so:system/vendor/lib/libmmcamera_isp_bf_stats44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_bg_stats44.so:system/vendor/lib/libmmcamera_isp_bg_stats44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_bhist_stats44.so:system/vendor/lib/libmmcamera_isp_bhist_stats44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_bpc44.so:system/vendor/lib/libmmcamera_isp_bpc44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_chroma_enhan40.so:system/vendor/lib/libmmcamera_isp_chroma_enhan40.so \
    out/proprietary/vendor/lib/libmmcamera_isp_chroma_suppress40.so:system/vendor/lib/libmmcamera_isp_chroma_suppress40.so \
    out/proprietary/vendor/lib/libmmcamera_isp_clamp_encoder40.so:system/vendor/lib/libmmcamera_isp_clamp_encoder40.so \
    out/proprietary/vendor/lib/libmmcamera_isp_clamp_video40.so:system/vendor/lib/libmmcamera_isp_clamp_video40.so \
    out/proprietary/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so:system/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so \
    out/proprietary/vendor/lib/libmmcamera_isp_clf44.so:system/vendor/lib/libmmcamera_isp_clf44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_color_correct40.so:system/vendor/lib/libmmcamera_isp_color_correct40.so \
    out/proprietary/vendor/lib/libmmcamera_isp_color_xform_encoder40.so:system/vendor/lib/libmmcamera_isp_color_xform_encoder40.so \
    out/proprietary/vendor/lib/libmmcamera_isp_cs_stats44.so:system/vendor/lib/libmmcamera_isp_cs_stats44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_demosaic44.so:system/vendor/lib/libmmcamera_isp_demosaic44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_demux40.so:system/vendor/lib/libmmcamera_isp_demux40.so \
    out/proprietary/vendor/lib/libmmcamera_isp_fovcrop_encoder40.so:system/vendor/lib/libmmcamera_isp_fovcrop_encoder40.so \
    out/proprietary/vendor/lib/libmmcamera_isp_fovcrop_viewfinder40.so:system/vendor/lib/libmmcamera_isp_fovcrop_viewfinder40.so \
    out/proprietary/vendor/lib/libmmcamera_isp_gamma44.so:system/vendor/lib/libmmcamera_isp_gamma44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_ihist_stats44.so:system/vendor/lib/libmmcamera_isp_ihist_stats44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_linearization40.so:system/vendor/lib/libmmcamera_isp_linearization40.so \
    out/proprietary/vendor/lib/libmmcamera_isp_ltm44.so:system/vendor/lib/libmmcamera_isp_ltm44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_luma_adaptation40.so:system/vendor/lib/libmmcamera_isp_luma_adaptation40.so \
    out/proprietary/vendor/lib/libmmcamera_isp_mce40.so:system/vendor/lib/libmmcamera_isp_mce40.so \
    out/proprietary/vendor/lib/libmmcamera_isp_mesh_rolloff44.so:system/vendor/lib/libmmcamera_isp_mesh_rolloff44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_rs_stats44.so:system/vendor/lib/libmmcamera_isp_rs_stats44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_scaler_encoder44.so:system/vendor/lib/libmmcamera_isp_scaler_encoder44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_scaler_viewfinder44.so:system/vendor/lib/libmmcamera_isp_scaler_viewfinder44.so \
    out/proprietary/vendor/lib/libmmcamera_isp_sce40.so:system/vendor/lib/libmmcamera_isp_sce40.so \
    out/proprietary/vendor/lib/libmmcamera_isp_sub_module.so:system/vendor/lib/libmmcamera_isp_sub_module.so \
    out/proprietary/vendor/lib/libmmcamera_isp_wb40.so:system/vendor/lib/libmmcamera_isp_wb40.so \
    out/proprietary/vendor/lib/libmmcamera_pdafcamif.so:system/vendor/lib/libmmcamera_pdafcamif.so \
    out/proprietary/vendor/lib/libmmcamera_pdaf.so:system/vendor/lib/libmmcamera_pdaf.so \
    out/proprietary/vendor/lib/libmmcamera_ppbase_module.so:system/vendor/lib/libmmcamera_ppbase_module.so \
    out/proprietary/vendor/lib/libmmcamera_s5k3m2xm.so:system/vendor/lib/libmmcamera_s5k3m2xm.so \
    out/proprietary/vendor/lib/libmmcamera_s5k5e2evt1.so:system/vendor/lib/libmmcamera_s5k5e2evt1.so \
    out/proprietary/vendor/lib/libmmcamera_s5k5e2.so:system/vendor/lib/libmmcamera_s5k5e2.so \
    out/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    out/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    out/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    out/proprietary/vendor/lib/libmmcamera_vpu_module.so:system/vendor/lib/libmmcamera_vpu_module.so \
    out/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    out/proprietary/vendor/lib/libmm-disp-apis.so:system/vendor/lib/libmm-disp-apis.so \
    out/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    out/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    out/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    out/proprietary/vendor/lib/libmmparser_lite.so:system/vendor/lib/libmmparser_lite.so \
    out/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
    out/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    out/proprietary/vendor/lib/libmmqjpegdma.so:system/vendor/lib/libmmqjpegdma.so \
    out/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
    out/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    out/proprietary/vendor/lib/libois_lc898122.so:system/vendor/lib/libois_lc898122.so \
    out/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    out/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    out/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    out/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    out/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    out/proprietary/vendor/lib/libQBLAS-0.11.38.so:system/vendor/lib/libQBLAS-0.11.38.so \
    out/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    out/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    out/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    out/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    out/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    out/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    out/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    out/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    out/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    out/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    out/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    out/proprietary/vendor/lib/libqomx_jpegenc_pipe.so:system/vendor/lib/libqomx_jpegenc_pipe.so \
    out/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    out/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    out/proprietary/vendor/lib/libqti-iop-client.so:system/vendor/lib/libqti-iop-client.so \
    out/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    out/proprietary/vendor/lib/libqti_performance.so:system/vendor/lib/libqti_performance.so \
    out/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    out/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    out/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    out/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    out/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    out/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    out/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    out/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    out/proprietary/vendor/lib/libSonyIMX230PdafLibrary.so:system/vendor/lib/libSonyIMX230PdafLibrary.so \
    out/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    out/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    out/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    out/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    out/proprietary/vendor/lib/libvendorconn.so:system/vendor/lib/libvendorconn.so \
    out/proprietary/vendor/lib/libwqe.so:system/vendor/lib/libwqe.so \
    out/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    out/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    out/proprietary/vendor/lib/libxt_native.so:system/vendor/lib/libxt_native.so \
    out/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    out/proprietary/vendor/lib/sensors.ssc.so:system/vendor/lib/sensors.ssc.so \
    out/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    out/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    out/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    out/proprietary/vendor/qcril.db:system/vendor/qcril.db

PRODUCT_PACKAGES += \
    libril \
    libqmiservices \
    QtiTelephonyService \
    QtiTetherService \
    com.qti.dpmframework \
    com.qti.location.sdk \
    dpmapi \
    QPerformance \
    tcmclient
